fix: sync logic

diff --git a/commands/pull b/commands/pull
--- a/commands/pull
+++ b/commands/pull
@@ -4,10 +4,10 @@ help() {
   echo "Pull - pull source code from remote git repository with current branch"
   echo ""
   echo "Usage:"
-  echo "  ta pull [options...]"
+  echo "  project pull [options...]"
   echo ""
   echo "Options:"
-  echo "  --remote-branch <remote_branch>   Merge remote branch"
+  echo "  --upstream-branch <upstream_branch>   Merge remote branch"
 }
 
 core() {
@@ -15,8 +15,8 @@ core() {
     help
     exit 0
   fi
-  
-  local remote_branch=""
+
+  local upstream_branch=""
 
   while [[ $# -gt 0 ]]; do
     local key=$1
@@ -24,11 +24,11 @@ core() {
     case $key in
     -r | --remote-branch)
       if [ -z "$value" ]; then
-        log::error "[$(timestamp)] remote_branch is required, usage: --remote-branch <remote_branch>"
+        log::error "[$(timestamp)] upstream_branch is required, usage: --remote-branch <upstream_branch>"
         exit 1
       fi
 
-      os::set_var remote_branch $value
+      os::set_var upstream_branch $value
       shift
       shift
       ;;
@@ -43,7 +43,20 @@ core() {
     esac
   done
 
-  project::pull $remote_branch
+  local branch=$(git::branch)
+  log::info "[$(timestamp)] current branch: $branch ..."
+  if [ -n "$upstream_branch" ]; then
+    log::info "[$(timestamp)] upstream branch: $upstream_branch ..."
+  fi
+
+  log::info "[$(timestamp)] start to pull remote branch to local ..."
+  project::pull $upstream_branch
+  if [ "$?" != "0" ]; then
+    log::fail "[$(timestamp)] failed to to pull remote branch to local."
+    return 1
+  fi
+
+  log::success "[$(timestamp)] succeed to pull remote branch to local."
 }
 
 run() {
diff --git a/commands/sync b/commands/sync
--- a/commands/sync
+++ b/commands/sync
@@ -1,10 +1,10 @@
 #!/bin/bash
 
 help() {
-  echo "Sync - sync  current branch and put local to remote"
+  echo "Sync - sync current branch and put local to remote"
   echo ""
   echo "Usage:"
-  echo "  ta sync [options...] [upstream_branch]"
+  echo "  project sync [options...] [upstream_branch]"
   echo ""
   echo "Options:"
   echo "    --no-push   Don't push the branch to remote"
@@ -13,10 +13,17 @@ help() {
 core() {
   if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
     help
-    exit 0
+    return 0
   fi
 
+  log::info "[$(timestamp)] start to sync branch with remote <=> local ..."
   project::sync "$@"
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to sync branch with remote <=> local."
+    return 1
+  fi
+
+  log::success "[$(timestamp)] succeed to sync branch with remote <=> local."
 }
 
 run() {
diff --git a/core/merge_remote b/core/merge_remote
--- a/core/merge_remote
+++ b/core/merge_remote
@@ -1,33 +1,28 @@
 #!/bin/bash
 
-# project::merge_remote 如果是 feature，说明在开发功能，提交时可以自动 merge 远端当前峰值
-project::merge_remote() {
+# project::merge_upstream 如果是 feature，说明在开发功能，提交时可以自动 merge 远端当前峰值
+project::merge_upstream() {
   local upstream_branch=$1
+  local tmp_error=$(os::tmp_file)
+
   if [ -z "$upstream_branch" ]; then
-    upstream_branch=$(git::branch)
-  fi
-
-  local branch=$(git::branch)
-  # 如果远程存在当前分支
-  log::info "[$(timestamp)] 检查当前分支是否存在远程分支 ..."
-  if [ "$(git::has_branch ${branch})" = "true" ]; then
-    log::info "[$(timestamp)] 开始合并当前分支（${branch}）远程代码 ..."
-    os::git pull origin ${branch} --quiet
-    if [ "$?" != "0" ]; then
-      log::error "[$(timestamp)] 同步当前分支（${branch}）远程代码失败，请手动解决冲突后再提交."
-      return 1
-    fi
-  fi
-
-  log::info "[$(timestamp)] 开始合并 ${upstream_branch}"
-  os::git fetch origin >>/dev/null
-  os::git merge origin/${upstream_branch} --quiet
-  if [ "$?" != "0" ]; then
-    log::error "[$(timestamp)] 合并 ${upstream_branch} 失败，请手动解决冲突后再提交."
+    log::error "[$(timestamp)] upstream branch is required"
     return 1
   fi
 
-  log::success "[$(timestamp)] 合并 ${upstream_branch} 成功."
+  os::git fetch origin >>/dev/null 2>&$tmp_error
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp) failed to fetch origin."
+    cat $tmp_error
+    return 1
+  fi
+
+  os::git merge origin/${upstream_branch} --quiet >>/dev/null 2>&$tmp_error
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to merge origin branch"
+    cat $tmp_error
+    return 1
+  fi
 }
 
-export -f project::merge_remote
+export -f project::merge_upstream
diff --git a/core/push b/core/push
--- a/core/push
+++ b/core/push
@@ -1,21 +1,28 @@
 #!/bin/bash
 
 project::push() {
-  project::prepare
-
   # not a git repository
   if [ ! -d "$PWD/.git" ]; then
-    log::error "[$(timestamp)] 当前目录不是有效目录，请在仓库目录中执行该命令"
+    log::error "[$(timestamp)] current work directory is not a git repository."
     return 1
   fi
+
+  log::info "[$(timestamp)] ready to push ..."
 
   local branch=$(git::branch)
   if [ -z "$branch" ]; then
-    log::error "[$(timestamp)] 无法获取 Git Branch，请找管理员查看问题"
+    log::error "[$(timestamp)] cannot get local branch."
     return 1
   fi
 
+  log::info "[$(timestamp)] start to push local branch to remote ..."
   os::git push origin $branch
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)] failed to push local branch to remote."
+    return 1
+  fi
+
+  log::success "[$(timestamp)] succeed to push local branch to remote."
 }
 
 export -f project::push
diff --git a/core/sync b/core/sync
--- a/core/sync
+++ b/core/sync
@@ -1,29 +1,62 @@
 #!/bin/bash
 
-# commit 提交
+# project::sync syncs local and remote by p2p
 project::sync() {
   local upstream_branch=$1
   local repo_name=$(git::basename)
   local branch=$(git::branch)
 
-  log::info "[$(timestamp)] 当前分支: $branch ..."
+  local tmp_error=$(os::tmp_file)
 
-  # @TODO
-  if [ -z "$upstream_branch" ]; then
-    upstream_branch="$branch"
+  log::info "[$(timestamp)] current branch: $branch ..."
+
+  if [ "$(git::is_changed)" = "true" ]; then
+    log::info "[$(timestamp)] start to commit local change ..."
+    project::commit
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to commit local change ..."
+      cat $tmp_error
+      return 1
+    fi
+    log::success "[$(timestamp)] succeed to commit local change ..."
   fi
 
-  log::info "[$(timestamp)] 准备同步远程分支: $upstream_branch ..."
-  project::merge_remote $upstream_branch
-  if [ "$?" != "0" ]; then
-    return 1
+  log::info "[$(timestamp)] start to check whether remote branch exist ..."
+  if [ "$(git::has_branch ${branch})" = "true" ]; then
+    log::info "[$(timestamp)] found remote branch($branch) ..."
+    log::info "[$(timestamp)] start to pull remote branch to local ..."
+    project::pull >>/dev/null 2>$tmp_error
+    if [ "$?" != "0" ]; then
+      log::fail "[$(timestamp)] failed to to pull remote branch to local."
+      cat $tmp_error
+      return 1
+    fi
+    log::success "[$(timestamp)] succeed to pull remote branch to local."
+  else
+    log::info "[$(timestamp)] remote branch($branch) not found, ignore ..."
+  fi
+
+  if [ -n "$upstream_branch" ]; then
+    log::info "[$(timestamp)] start to merge upstream branch($upstream_branch) to loccal ..."
+    project::merge_upstream $upstream_branch >>/dev/null 2>$tmp_error
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to merge upstream branch($upstream_branch) to local."
+      cat $tmp_error
+      return 1
+    fi
+    log::success "[$(timestamp)] succeed to merge upstream branch($upstream_branch) to local."
   fi
 
   if [ "$no_push" != "true" ]; then
-    project::commit_push
+    log::info "[$(timestamp)] start to push local branch($branch) to remote ..."
+    project::push >>/dev/null 2>$tmp_error
     if [ "$?" != "0" ]; then
+      log::success "[$(timestamp)] failed to push local branch($branch) to remote."
+      cat $tmp_error
       return 1
     fi
+
+    log::success "[$(timestamp)] succeed to push local branch($branch) to remote."
   fi
 }
 
