feat(release): support custom release ./bin/zmicro/release

diff --git a/core/release b/core/release
--- a/core/release
+++ b/core/release
@@ -4,6 +4,17 @@ project::release() {
   # apply proxy
   net::using_smart_proxy
 
+  # ./bin/zmicro/release
+  local custom_release="$(project::find_command release)"
+  if [ -n "$custom_release" ]; then
+    project::run_command release "${@:2}"
+    if [ "$?" != "0" ]; then
+      log::error "[$(timestamp)] failed to release project."
+      return 1
+    fi
+    return 0
+  fi
+
   local path=$1
   if [ -z "$path" ]; then
     log::error "[$(timestamp)] project path is required."
